import React from "react";
import { AbsoluteFill, Img, staticFile, useVideoConfig } from "remotion";
import { NIGHT, PAPER } from "../palette";

/**
 * The two grounds. Both are plain HTML/CSS/SVG layers under a scene's <svg> —
 * cheap to paint every frame, and the texture PNGs are generated by
 * `scripts/textures.mjs` from seeded noise, never downloaded.
 *
 * Every size here comes from the composition (`useVideoConfig`), so the same
 * ground serves the 1920×1080 film and the 1080×1920 vertical cuts; a portrait
 * frame picks the `-tall` textures.
 */

const useFrameSize = () => {
  const { width, height } = useVideoConfig();
  return { W: width, H: height, tall: height > width };
};

/** Warm paper with wide pastel diagonal stripes, drifting very slowly. */
export const PaperGround: React.FC<{
  frame: number;
  stripe: string;
  band?: number;
}> = ({ frame, stripe, band = 118 }) => {
  const { W, H } = useFrameSize();
  // An SVG pattern, not a CSS gradient: a pattern tiles without end, so the
  // drift never opens a seam at the frame's edge the way a shifted
  // `background-position` on a frame-sized gradient does.
  const drift = (frame * 0.3) % (band * 2);
  return (
    <AbsoluteFill style={{ backgroundColor: PAPER.cream }}>
      <svg width={W} height={H} style={{ position: "absolute", inset: 0 }}>
        <defs>
          <pattern
            id={`stripes-${stripe.slice(1)}`}
            width={band * 2}
            height={40}
            patternUnits="userSpaceOnUse"
            patternTransform={`rotate(36) translate(${drift} 0)`}
          >
            <rect width={band} height={40} fill={PAPER.cream} />
            <rect x={band} width={band} height={40} fill={stripe} />
          </pattern>
        </defs>
        <rect width={W} height={H} fill={`url(#stripes-${stripe.slice(1)})`} />
      </svg>
    </AbsoluteFill>
  );
};

/** The paper itself — multiplied over everything on a paper chapter. */
export const PaperTexture: React.FC = () => {
  const { W, H, tall } = useFrameSize();
  return (
    <AbsoluteFill style={{ mixBlendMode: "multiply", pointerEvents: "none" }}>
      <Img src={staticFile(`tex/paper${tall ? "-tall" : ""}.png`)} style={{ width: W, height: H }} />
    </AbsoluteFill>
  );
};

/** Navy blueprint: a lifted centre, a two-weight grid, mottling, rulers and brackets. */
export const NightGround: React.FC<{
  frame: number;
  centre?: [number, number];
}> = ({ frame, centre = [50, 46] }) => {
  const { W, H, tall } = useFrameSize();
  const [cx, cy] = centre;
  return (
    <AbsoluteFill style={{ backgroundColor: NIGHT.deep }}>
      <AbsoluteFill
        style={{
          background: `radial-gradient(ellipse ${tall ? "95% 70%" : "75% 85%"} at ${cx}% ${cy}%, ${NIGHT.lift} 0%, ${NIGHT.mid} 42%, ${NIGHT.deep} 100%)`,
        }}
      />
      <AbsoluteFill
        style={{
          backgroundImage: [
            `linear-gradient(${NIGHT.gridMajor} 1px, transparent 1px)`,
            `linear-gradient(90deg, ${NIGHT.gridMajor} 1px, transparent 1px)`,
            `linear-gradient(${NIGHT.grid} 1px, transparent 1px)`,
            `linear-gradient(90deg, ${NIGHT.grid} 1px, transparent 1px)`,
          ].join(","),
          backgroundSize: "240px 240px, 240px 240px, 48px 48px, 48px 48px",
          backgroundPosition: "0px 12px, 0px 12px, 0px 12px, 0px 12px",
        }}
      />
      <AbsoluteFill style={{ mixBlendMode: "screen", opacity: 0.22 }}>
        <Img src={staticFile(`tex/night${tall ? "-tall" : ""}.png`)} style={{ width: W, height: H }} />
      </AbsoluteFill>
      <BlueprintFurniture frame={frame} W={W} H={H} />
    </AbsoluteFill>
  );
};

/** Corner brackets, edge rulers and faint compass circles — the drafting-table furniture. */
const BlueprintFurniture: React.FC<{ frame: number; W: number; H: number }> = ({ frame, W, H }) => {
  const tall = H > W;
  const rulerTop = tall ? 280 : 120;
  const rulerBottom = H - (tall ? 280 : 120);
  const baseY = H - 40;
  const baseL = tall ? 120 : 180;
  const baseR = W - baseL;
  const ticks: React.ReactNode[] = [];
  for (let y = rulerTop; y <= rulerBottom; y += 24) {
    const major = (y - rulerTop) % 120 === 0;
    ticks.push(
      <line key={`l${y}`} x1={52} x2={major ? 70 : 60} y1={y} y2={y} stroke={NIGHT.lineFaint} strokeWidth={1.2} />,
    );
  }
  for (let x = baseL; x <= baseR; x += 24) {
    const major = (x - baseL) % 120 === 0;
    ticks.push(
      <line
        key={`b${x}`}
        x1={x}
        x2={x}
        y1={baseY}
        y2={major ? baseY - 18 : baseY - 10}
        stroke={NIGHT.lineFaint}
        strokeWidth={1.2}
      />,
    );
  }
  const bracket = (x: number, y: number, sx: number, sy: number) => (
    <path d={`M${x} ${y + sy * 22} V${y} H${x + sx * 22}`} fill="none" stroke={NIGHT.lineDim} strokeWidth={1.6} />
  );
  const spin = frame * 0.02;
  const ccx = W / 2;
  const ccy = H * 0.52;
  const k = Math.min(W, H) / 1080;
  return (
    <svg width={W} height={H} style={{ position: "absolute", inset: 0 }}>
      <g opacity={0.9}>
        {bracket(36, 36, 1, 1)}
        {bracket(W - 36, 36, -1, 1)}
        {bracket(36, H - 36, 1, -1)}
        {bracket(W - 36, H - 36, -1, -1)}
      </g>
      <line x1={52} x2={52} y1={rulerTop} y2={rulerBottom} stroke={NIGHT.lineFaint} strokeWidth={1.2} />
      <line x1={baseL} x2={baseR} y1={baseY} y2={baseY} stroke={NIGHT.lineFaint} strokeWidth={1.2} />
      {ticks}
      <g transform={`rotate(${spin} ${ccx} ${ccy})`} fill="none" stroke={NIGHT.lineFaint} strokeWidth={1.1}>
        <circle cx={ccx} cy={ccy} r={330 * k} strokeDasharray="2 10" />
        <circle cx={ccx} cy={ccy} r={520 * k} />
        <circle cx={ccx} cy={ccy} r={760 * k} strokeDasharray="1 14" />
      </g>
    </svg>
  );
};

/** Film grain + a gentle vignette over the whole frame. */
export const FilmOverlay: React.FC<{
  frame: number;
  ground: "paper" | "night";
}> = ({ frame, ground }) => {
  // New grain every other frame, at a pseudo-random offset.
  const step = Math.floor(frame / 2);
  const ox = (step * 397) % 1024;
  const oy = (step * 613) % 1024;
  return (
    <>
      <AbsoluteFill
        style={{
          backgroundImage: `url(${staticFile("tex/grain.png")})`,
          backgroundSize: "1024px 1024px",
          backgroundPosition: `${ox}px ${oy}px`,
          mixBlendMode: ground === "paper" ? "soft-light" : "overlay",
          opacity: ground === "paper" ? 0.22 : 0.18,
          pointerEvents: "none",
        }}
      />
      <AbsoluteFill
        style={{
          background:
            ground === "paper"
              ? "radial-gradient(ellipse 80% 80% at 50% 48%, rgba(0,0,0,0) 60%, rgba(70,45,25,0.16) 100%)"
              : "radial-gradient(ellipse 80% 80% at 50% 48%, rgba(0,0,0,0) 55%, rgba(0,0,8,0.45) 100%)",
          pointerEvents: "none",
        }}
      />
    </>
  );
};
